# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task_list', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, help_text='Текстовое описание задачи', max_length=100, verbose_name='Текстовое описание задачи'),
        ),
    ]
