# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task_list', '0003_auto_20170825_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, help_text='Текстовое описание задачи', max_length=2000, verbose_name='Текстовое описание задачи'),
        ),
    ]
