FROM nginx:latest

# Автор образа:
MAINTAINER Ivan Golubykh <ivan9@allworld.xyz>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
#RUN apt-get update && apt-get install --assume-yes apt-utils
RUN apt-get install --assume-yes apt-utils
RUN apt-get install -y dialog;

RUN apt-get install -y --no-install-recommends \
        iproute2 \
        iputils-ping \
        mc \
        htop; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        wget \
        gcc \
        g++ \
        make \
        libc6-dev; \
    apt-get install -y --no-install-recommends \
        libc-dev \
        gnupg \
        libaio1 \
        aptitude \
        zlib1g-dev \
        linux-libc-dev; \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip \
        default-libmysqlclient-dev; \
    pip3 install --upgrade pip; \
    pip3 install setuptools

RUN mkdir -p /usr/share/nginx/django
RUN mkdir -p /usr/share/nginx/django_logs
WORKDIR /usr/share/nginx/django

COPY ["./requirements.txt","/usr/share/nginx/"]
RUN pip3 install --no-cache-dir -r ../requirements.txt
COPY ./django_start_script.sh /usr/share/nginx/

ENV DEBIAN_FRONTEND teletype
ENV TERM=linux

# Комманда запуска по умолчанию (выполняется только одна, последняя):
#CMD ["uwsgi","--http", ":8000", "--wsgi-file", "bizmart_ru/wsgi.py"]
#CMD ["python3","manage.py","runserver","--http",":8000"]
CMD ["../django_start_script.sh"]
